# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

# [[main]]
#  name = "Publications"
#  pageRef = "/#publications"
#  weight = 20

[[main]]
 name = "Blog"
 pageRef = "/blog"
 weight = 40


# [[main]]
#  name = "Contact"
#  pageRef = "/contact"
#  weight = 40


[[main]]
 name = "Renoir"
 pageRef = "/renoir"
 weight = 10

[[main]]
 name = "Contact"
 pageRef = "/about"
 weight = 50

[[main]]
 name = "Documentation"
 parent = "Renoir"
 pageRef = "/book"
 weight = 2

[[main]]
 name = "Reference"
 parent = "Renoir"
 url = "https://deib-polimi.github.io/renoir/renoir/"
 weight = 3

[[main]]
 name = "Overview"
 parent = "Renoir"
 pageRef = "/renoir"
 weight = 1


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
